from django.core.management.base import BaseCommand
from django.utils.text import slugify

from core.models import Book, Category, Electronics, Fashion, Product


class Command(BaseCommand):
    help = "Seed categories and products for local testing"

    def handle(self, *args, **options):
        categories = {
            "Book": Category.objects.get_or_create(name="Book")[0],
            "Electronics": Category.objects.get_or_create(name="Electronics")[0],
            "Fashion": Category.objects.get_or_create(name="Fashion")[0],
        }

        products = [
            # ================= BOOKS (5 items) =================
            {
                "name": "Clean Code",
                "sku": "BOOK-CC-001",
                "price": 15.0,
                "discount_percent": 10,
                "stock": 50,
                "sold_count": 210,
                "rating_avg": 4.8,
                "rating_count": 142,
                "domain": "book",
                "category": categories["Book"],
                "brand": "Prentice Hall",
                "short_description": "Sach kinh dien ve ky thuat viet code sach va de bao tri.",
                "description": "Cuon sach noi tieng ve nguyen tac va thuc hanh clean code cho lap trinh vien.",
                "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Robert C. Martin",
                    "publisher": "Prentice Hall",
                    "isbn": "9780132350884",
                    "pages": 464,
                    "language": "English",
                    "published_year": 2008,
                },
            },
            {
                "name": "Introduction to Algorithms",
                "sku": "BOOK-ITA-002",
                "price": 25.0,
                "discount_percent": 5,
                "stock": 30,
                "sold_count": 156,
                "rating_avg": 4.7,
                "rating_count": 98,
                "domain": "book",
                "category": categories["Book"],
                "brand": "MIT Press",
                "short_description": "Giao trinh thuat toan kinh dien cho sinh vien CNTT.",
                "description": "Noi dung day du ve cau truc du lieu, thuat toan va phan tich do phuc tap.",
                "image_url": "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Thomas H. Cormen",
                    "publisher": "MIT Press",
                    "isbn": "9780262046305",
                    "pages": 1312,
                    "language": "English",
                    "published_year": 2022,
                },
            },
            {
                "name": "The Pragmatic Programmer",
                "sku": "BOOK-TPP-003",
                "price": 22.0,
                "discount_percent": 8,
                "stock": 45,
                "sold_count": 190,
                "rating_avg": 4.9,
                "rating_count": 115,
                "domain": "book",
                "category": categories["Book"],
                "brand": "Addison-Wesley",
                "short_description": "Hanh trinh tu tho phu den tho ca lap trinh chuyen nghiep.",
                "description": "Cuon sach giup ban tro thanh lap trinh vien gioi hon, hieu qua hon va thich ung tot hon.",
                "image_url": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Andrew Hunt",
                    "publisher": "Addison-Wesley",
                    "isbn": "9780135957059",
                    "pages": 352,
                    "language": "English",
                    "published_year": 2019,
                },
            },
            {
                "name": "Design Patterns",
                "sku": "BOOK-DP-004",
                "price": 28.0,
                "discount_percent": 12,
                "stock": 25,
                "sold_count": 89,
                "rating_avg": 4.7,
                "rating_count": 64,
                "domain": "book",
                "category": categories["Book"],
                "brand": "Addison-Wesley",
                "short_description": "Mau thiet ke huong doi tuong kinh dien tu Gang of Four.",
                "description": "Cuon sach bat hu gioi thieu 23 mau thiet ke giup giai quyet cac bai toan lap trinh pho bien.",
                "image_url": "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Erich Gamma",
                    "publisher": "Addison-Wesley",
                    "isbn": "9780201633610",
                    "pages": 395,
                    "language": "English",
                    "published_year": 1994,
                },
            },
            {
                "name": "Refactoring Code",
                "sku": "BOOK-REF-005",
                "price": 20.0,
                "discount_percent": 15,
                "stock": 35,
                "sold_count": 76,
                "rating_avg": 4.8,
                "rating_count": 43,
                "domain": "book",
                "category": categories["Book"],
                "brand": "Addison-Wesley",
                "short_description": "Cai thien thiet ke cua ma nguon hien co cuc ky hieu qua.",
                "description": "Sach cua Martin Fowler gioi thieu cac ky thuat refactor code thuc te giup nang cao chat luong he thong.",
                "image_url": "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Martin Fowler",
                    "publisher": "Addison-Wesley",
                    "isbn": "9780134757599",
                    "pages": 448,
                    "language": "English",
                    "published_year": 2018,
                },
            },
            {
                "name": "Code Complete 2",
                "sku": "BOOK-CC2-006",
                "price": 30.0,
                "discount_percent": 10,
                "stock": 40,
                "sold_count": 92,
                "rating_avg": 4.8,
                "rating_count": 55,
                "domain": "book",
                "category": categories["Book"],
                "brand": "Microsoft Press",
                "short_description": "Thuc hanh ky thuat xay dung phan mem tuyet voi va thuc te.",
                "description": "Cuon cam nang phai co cho moi lap trinh vien chuyen nghiep, huong dan toan dien ve lap trinh.",
                "image_url": "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Steve McConnell",
                    "publisher": "Microsoft Press",
                    "isbn": "9780735619678",
                    "pages": 960,
                    "language": "English",
                    "published_year": 2004,
                },
            },
            {
                "name": "Clean Architecture",
                "sku": "BOOK-CA-007",
                "price": 24.0,
                "discount_percent": 8,
                "stock": 38,
                "sold_count": 88,
                "rating_avg": 4.7,
                "rating_count": 47,
                "domain": "book",
                "category": categories["Book"],
                "brand": "Prentice Hall",
                "short_description": "Huong dan cua nghe nhan ve cau truc va thiet ke phan mem.",
                "description": "Cuon sach truyen tai nhung nguyen tac thiet ke kien truc phan mem cot loi cua Uncle Bob.",
                "image_url": "https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "author": "Robert C. Martin",
                    "publisher": "Prentice Hall",
                    "isbn": "9780134494166",
                    "pages": 432,
                    "language": "English",
                    "published_year": 2017,
                },
            },

            # ================= ELECTRONICS (LAPTOPS - 4 items) =================
            {
                "name": "Gaming Laptop Pro 15",
                "sku": "ELEC-LAP-101",
                "price": 1200.0,
                "discount_percent": 15,
                "stock": 20,
                "sold_count": 73,
                "rating_avg": 4.6,
                "rating_count": 55,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Acer",
                "short_description": "Laptop gaming RTX hieu nang cao cho hoc tap va giai tri.",
                "description": "CPU Intel Core i7, card do hoa roi RTX 4060, RAM 16GB, SSD 1TB toc do cao.",
                "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Acer",
                    "warranty": 24,
                    "model_name": "Predator Helios",
                    "ram": "16GB",
                    "storage": "1TB SSD",
                    "chip": "Intel Core i7",
                    "screen_size": "15.6\"",
                    "battery": "90Wh",
                    "origin": "Vietnam",
                },
            },
            {
                "name": "MacBook Air M2 Silver",
                "sku": "ELEC-LAP-103",
                "price": 999.0,
                "discount_percent": 10,
                "stock": 15,
                "sold_count": 140,
                "rating_avg": 4.9,
                "rating_count": 210,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Apple",
                "short_description": "Laptop mong nhe, sang trong voi chip Apple M2 cuc manh.",
                "description": "Chip M2 dot pha, RAM 8GB, SSD 256GB, thoi luong pin len toi 18 tieng lam viec lien tuc.",
                "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Apple",
                    "warranty": 12,
                    "model_name": "MacBook Air M2",
                    "ram": "8GB",
                    "storage": "256GB SSD",
                    "chip": "Apple M2",
                    "screen_size": "13.6\"",
                    "battery": "52.6Wh",
                    "origin": "China",
                },
            },
            {
                "name": "Laptop HP Pavilion Elite",
                "sku": "ELEC-LAP-104",
                "price": 750.0,
                "discount_percent": 5,
                "stock": 25,
                "sold_count": 62,
                "rating_avg": 4.4,
                "rating_count": 48,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "HP",
                "short_description": "Laptop van phong cao cap, thiet ke nhom nguyen khoi.",
                "description": "Laptop HP sang trong, trang bi chip AMD Ryzen 5, RAM 16GB, man hinh IPS Full HD sac net.",
                "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "HP",
                    "warranty": 12,
                    "model_name": "Pavilion 14",
                    "ram": "16GB",
                    "storage": "512GB SSD",
                    "chip": "Ryzen 5 5600U",
                    "screen_size": "14\"",
                    "battery": "43Wh",
                    "origin": "China",
                },
            },
            {
                "name": "Asus ROG Gaming Beast",
                "sku": "ELEC-LAP-105",
                "price": 1650.0,
                "discount_percent": 18,
                "stock": 10,
                "sold_count": 35,
                "rating_avg": 4.8,
                "rating_count": 27,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Asus",
                "short_description": "Quai thu gaming RTX 4070 hieu nang cuc han, do hoa đỉnh cao.",
                "description": "Asus ROG Strix hiêu nang gaming tối thuong: Intel i9, RTX 4070, RAM 32GB, tan nhiet ba quat.",
                "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Asus",
                    "warranty": 24,
                    "model_name": "ROG Strix G16",
                    "ram": "32GB",
                    "storage": "1TB NVMe SSD",
                    "chip": "Intel Core i9 13th Gen",
                    "screen_size": "16\"",
                    "battery": "90Wh",
                    "origin": "Taiwan",
                },
            },
            {
                "name": "Lenovo ThinkPad X1 Carbon",
                "sku": "ELEC-LAP-109",
                "price": 1599.0,
                "discount_percent": 12,
                "stock": 8,
                "sold_count": 22,
                "rating_avg": 4.9,
                "rating_count": 18,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Lenovo",
                "short_description": "Laptop doanh nhan sieu cao cap, ban phim dinh nhat the gioi.",
                "description": "Thiet ke soi carbon sieu ben va sieu nhe, bao mat van tay, man hinh OLED 2.8K sac net.",
                "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Lenovo",
                    "warranty": 36,
                    "model_name": "ThinkPad X1 Carbon Gen 11",
                    "ram": "32GB",
                    "storage": "1TB SSD",
                    "chip": "Intel Core i7 1365U",
                    "screen_size": "14\"",
                    "battery": "57Wh",
                    "origin": "Japan",
                },
            },
            {
                "name": "Dell XPS 13 OLED",
                "sku": "ELEC-LAP-110",
                "price": 1450.0,
                "discount_percent": 10,
                "stock": 12,
                "sold_count": 45,
                "rating_avg": 4.7,
                "rating_count": 36,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Dell",
                "short_description": "Sieu pham laptop sieu mong nhe, viền man hinh sieu mong.",
                "description": "Man hinh vo cuc InfinityEdge OLED cam ung, sang trong bac nhat thi truong.",
                "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Dell",
                    "warranty": 12,
                    "model_name": "XPS 13 9315",
                    "ram": "16GB",
                    "storage": "512GB SSD",
                    "chip": "Intel Core i5 1230U",
                    "screen_size": "13.4\"",
                    "battery": "51Wh",
                    "origin": "USA",
                },
            },

            # ================= ELECTRONICS (SMARTPHONES - 4 items) =================
            {
                "name": "Smartphone X Plus",
                "sku": "ELEC-PHO-102",
                "price": 650.0,
                "discount_percent": 8,
                "stock": 40,
                "sold_count": 185,
                "rating_avg": 4.5,
                "rating_count": 121,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Samsung",
                "short_description": "Dien thoai camera sieu dep, man hinh AMOLED sac net.",
                "description": "Thiet ke cao cap, camera 50MP mat sau, ho tro sac nhanh 45W, pin 5000mAh.",
                "image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Samsung",
                    "warranty": 12,
                    "model_name": "Galaxy S23",
                    "ram": "8GB",
                    "storage": "256GB",
                    "chip": "Snapdragon 8 Gen 2",
                    "screen_size": "6.1\"",
                    "battery": "3900mAh",
                    "origin": "Korea",
                },
            },
            {
                "name": "iPhone 15 Pro Max Titan",
                "sku": "ELEC-PHO-106",
                "price": 1199.0,
                "discount_percent": 5,
                "stock": 18,
                "sold_count": 94,
                "rating_avg": 4.9,
                "rating_count": 87,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Apple",
                "short_description": "Sieu pham titan tu nha Apple, camera zoom quang hoc 5x.",
                "description": "Vo titan sieu nhe, chip Apple A17 Pro sieu manh, camera 48MP va nut Action Button moi.",
                "image_url": "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Apple",
                    "warranty": 12,
                    "model_name": "iPhone 15 Pro Max",
                    "ram": "8GB",
                    "storage": "256GB NVMe",
                    "chip": "Apple A17 Pro",
                    "screen_size": "6.7\"",
                    "battery": "4441mAh",
                    "origin": "China",
                },
            },
            {
                "name": "Xiaomi Redmi Note 13",
                "sku": "ELEC-PHO-107",
                "price": 249.0,
                "discount_percent": 15,
                "stock": 45,
                "sold_count": 132,
                "rating_avg": 4.4,
                "rating_count": 59,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Xiaomi",
                "short_description": "Dien thoai gia re, hieu nang cuc tot trong tam gia.",
                "description": "Trang bi camera 108MP sieu net, man hinh 120Hz muot ma va sac nhanh 33W.",
                "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Xiaomi",
                    "warranty": 18,
                    "model_name": "Redmi Note 13",
                    "ram": "6GB",
                    "storage": "128GB",
                    "chip": "Dimensity 6080",
                    "screen_size": "6.67\"",
                    "battery": "5000mAh",
                    "origin": "China",
                },
            },
            {
                "name": "Google Pixel 8 Pro",
                "sku": "ELEC-PHO-108",
                "price": 899.0,
                "discount_percent": 10,
                "stock": 12,
                "sold_count": 58,
                "rating_avg": 4.8,
                "rating_count": 42,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Google",
                "short_description": "Dien thoai Android thuan khiet voi AI Gemini tich hop.",
                "description": "Camera chup anh top 1 thi truong, ho tro cap nhat he dieu hanh 7 nam lien tuc tu Google.",
                "image_url": "https://images.unsplash.com/photo-1565630916779-e303be97b6f5?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Google",
                    "warranty": 12,
                    "model_name": "Pixel 8 Pro",
                    "ram": "12GB",
                    "storage": "128GB",
                    "chip": "Google Tensor G3",
                    "screen_size": "6.7\"",
                    "battery": "5050mAh",
                    "origin": "USA",
                },
            },
            {
                "name": "Samsung Galaxy S24 Ultra",
                "sku": "ELEC-PHO-111",
                "price": 1299.0,
                "discount_percent": 5,
                "stock": 14,
                "sold_count": 68,
                "rating_avg": 4.9,
                "rating_count": 52,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "Samsung",
                "short_description": "Sieu pham Galaxy AI camera 200MP và but S Pen doc ban.",
                "description": "Vo titan sieu ben, tich hop cac tinh nang AI thong minh: phien dich truc tiep, khoanh tron tim kiem.",
                "image_url": "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "Samsung",
                    "warranty": 12,
                    "model_name": "Galaxy S24 Ultra",
                    "ram": "12GB",
                    "storage": "256GB",
                    "chip": "Snapdragon 8 Gen 3",
                    "screen_size": "6.8\"",
                    "battery": "5000mAh",
                    "origin": "Vietnam",
                },
            },
            {
                "name": "OnePlus 12 Pro Max",
                "sku": "ELEC-PHO-112",
                "price": 799.0,
                "discount_percent": 10,
                "stock": 22,
                "sold_count": 47,
                "rating_avg": 4.7,
                "rating_count": 31,
                "domain": "electronics",
                "category": categories["Electronics"],
                "brand": "OnePlus",
                "short_description": "Kẻ sat thu flagship, sac sieu toc 100W, hieu nang vo song.",
                "description": "Camera Hasselblad the he moi, mat lung kinh nhám sang trong, pin cuc trau.",
                "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "brand": "OnePlus",
                    "warranty": 12,
                    "model_name": "OnePlus 12",
                    "ram": "16GB",
                    "storage": "512GB",
                    "chip": "Snapdragon 8 Gen 3",
                    "screen_size": "6.82\"",
                    "battery": "5400mAh",
                    "origin": "China",
                },
            },

            # ================= FASHION (CLOTHES - 4 items) =================
            {
                "name": "Basic T-Shirt Cotton",
                "sku": "FAS-TSH-201",
                "price": 12.0,
                "discount_percent": 20,
                "stock": 100,
                "sold_count": 480,
                "rating_avg": 4.4,
                "rating_count": 260,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Local Brand",
                "short_description": "Ao thun basic cotton mem, phu hop mac hang ngay.",
                "description": "Ao thun chat lieu cotton 2 chieu thoang mat, form dang regular de phoi.",
                "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "M",
                    "color": "Black",
                    "material": "Cotton",
                    "gender": "Unisex",
                    "style": "Basic",
                },
            },
            {
                "name": "Premium Leather Jacket",
                "sku": "FAS-JAC-203",
                "price": 85.0,
                "discount_percent": 10,
                "stock": 20,
                "sold_count": 42,
                "rating_avg": 4.7,
                "rating_count": 31,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Zara Style",
                "short_description": "Ao khoac da PU cao cap, thoi trang lich lam.",
                "description": "Ao khoac da nam tinh, khoa keo thep chong gi, dem lot polyester em ai.",
                "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "L",
                    "color": "Deep Black",
                    "material": "PU Leather",
                    "gender": "Men",
                    "style": "Modern Jacket",
                },
            },
            {
                "name": "Slim Fit Denim Jeans",
                "sku": "FAS-JNS-204",
                "price": 32.0,
                "discount_percent": 15,
                "stock": 50,
                "sold_count": 112,
                "rating_avg": 4.5,
                "rating_count": 78,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Levi Clone",
                "short_description": "Quan jeans slim fit chat co dan, ben mau.",
                "description": "Quan jeans denim cao cap, ong con vua van, phong cach tre trung va linh hoat.",
                "image_url": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "32",
                    "color": "Indigo Blue",
                    "material": "Denim Cotton",
                    "gender": "Men",
                    "style": "Slim Fit",
                },
            },
            {
                "name": "Oversized Hoodie Classic",
                "sku": "FAS-HOD-206",
                "price": 35.0,
                "discount_percent": 8,
                "stock": 40,
                "sold_count": 125,
                "rating_avg": 4.6,
                "rating_count": 67,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Champion Clone",
                "short_description": "Ao Hoodie rong phong cach han quoc day dan am ap.",
                "description": "Ao khoac hoodie chat lieu ni bong cotton, mu rong, giu nhiet tot cho mua dong lanh.",
                "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "XL",
                    "color": "Gray/Melt",
                    "material": "Fleece Cotton",
                    "gender": "Unisex",
                    "style": "Streetwear Hoodie",
                },
            },
            {
                "name": "Polo Shirt Premium",
                "sku": "FAS-POL-209",
                "price": 18.0,
                "discount_percent": 5,
                "stock": 80,
                "sold_count": 145,
                "rating_avg": 4.5,
                "rating_count": 82,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Local Brand",
                "short_description": "Ao Polo nam cao cap co be, phong cach thanh lich.",
                "description": "Chat lieu cotton pique co gian tot, tham hut mo hoi phu hop di lam va choi golf.",
                "image_url": "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "L",
                    "color": "Navy Blue",
                    "material": "Pique Cotton",
                    "gender": "Men",
                    "style": "Smart Casual",
                },
            },
            {
                "name": "Winter Wool Coat",
                "sku": "FAS-COT-210",
                "price": 95.0,
                "discount_percent": 15,
                "stock": 15,
                "sold_count": 28,
                "rating_avg": 4.8,
                "rating_count": 20,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Zara Style",
                "short_description": "Măng to dạ len dang dai sang trong cho mua dong.",
                "description": "Ao khoac da len nu cao cap giu am tuyet doi, thoi trang Chau Au thanh lich quy phai.",
                "image_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "M",
                    "color": "Camel",
                    "material": "Premium Wool",
                    "gender": "Women",
                    "style": "Elegant Long Coat",
                },
            },

            # ================= FASHION (SHOES - 4 items) =================
            {
                "name": "Running Shoes AirSpeed",
                "sku": "FAS-SHO-202",
                "price": 45.0,
                "discount_percent": 12,
                "stock": 60,
                "sold_count": 320,
                "rating_avg": 4.6,
                "rating_count": 187,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Sportline",
                "short_description": "Giay chay bo chuyen nghiep sieu nhe, de em chan.",
                "description": "De giay cao su chong tron truot, chat vai det mesh sieu thoang khi phu hop chay bo.",
                "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "42",
                    "color": "Red/White",
                    "material": "Mesh + Rubber",
                    "gender": "Men",
                    "style": "Sport",
                },
            },
            {
                "name": "Sneakers Ultraboost Sport",
                "sku": "FAS-SHO-205",
                "price": 110.0,
                "discount_percent": 20,
                "stock": 15,
                "sold_count": 65,
                "rating_avg": 4.8,
                "rating_count": 52,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Adidas Style",
                "short_description": "Giay sneaker de dem boost nang dong, di cuc thich.",
                "description": "Giay the thao sieu em, de giay lam tu dem bot nang luong doc quyen di rat thoai mai.",
                "image_url": "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "41",
                    "color": "Gray/Black",
                    "material": "Primeknit + Boost",
                    "gender": "Unisex",
                    "style": "Sneakers",
                },
            },
            {
                "name": "Canvas Sneakers Retro",
                "sku": "FAS-SHO-207",
                "price": 28.0,
                "discount_percent": 5,
                "stock": 40,
                "sold_count": 139,
                "rating_avg": 4.5,
                "rating_count": 63,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Converse Style",
                "short_description": "Giay co thap canvas retro co dien, nang dong tre trung.",
                "description": "Giay canvas de bang thich hop di hoc, di choi, phoi do cuc ky phong cach va don gian.",
                "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "40",
                    "color": "White/Gum",
                    "material": "Canvas + Rubber",
                    "gender": "Unisex",
                    "style": "Casual Sneakers",
                },
            },
            {
                "name": "Oxford Leather Dress Shoes",
                "sku": "FAS-SHO-208",
                "price": 65.0,
                "discount_percent": 10,
                "stock": 16,
                "sold_count": 38,
                "rating_avg": 4.6,
                "rating_count": 22,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Zara Style",
                "short_description": "Giay da Tay Oxford lich lam sang trong cho quy ong.",
                "description": "Giay da thiet ke buoc day Oxford co dien, chat lieu da bo that mem mai, de go chong mon.",
                "image_url": "https://images.unsplash.com/photo-1486308512493-ae6a1e9a10c4?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "42",
                    "color": "Coffee Brown",
                    "material": "Cow Leather",
                    "gender": "Men",
                    "style": "Classic Formal",
                },
            },
            {
                "name": "Adventure Hiking Boots",
                "sku": "FAS-SHO-211",
                "price": 75.0,
                "discount_percent": 10,
                "stock": 25,
                "sold_count": 42,
                "rating_avg": 4.7,
                "rating_count": 33,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Sportline",
                "short_description": "Giay leo nui da chong tham nuoc, de Vibram sieu bam.",
                "description": "Giay phuot outdoor chuyen nghiep chong va dap ngon chan, nang do co chan toi uu.",
                "image_url": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "43",
                    "color": "Army Green",
                    "material": "Waterproof Leather + Vibram Sole",
                    "gender": "Unisex",
                    "style": "Outdoor / Hiking",
                },
            },
            {
                "name": "Classic Leather Sandals",
                "sku": "FAS-SHO-212",
                "price": 22.0,
                "discount_percent": 5,
                "stock": 45,
                "sold_count": 93,
                "rating_avg": 4.4,
                "rating_count": 27,
                "domain": "fashion",
                "category": categories["Fashion"],
                "brand": "Local Brand",
                "short_description": "Sandal da bo that thoi trang, mat me va phong tran.",
                "description": "Quai da bo thiet ke om chan mem mai, de xop PU sieu nhẹ chong tron truot di mua he.",
                "image_url": "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=600&q=80",
                "detail": {
                    "size": "40",
                    "color": "Brown",
                    "material": "Cowhide Leather + PU",
                    "gender": "Unisex",
                    "style": "Casual Summer",
                },
            }
        ]

        for item in products:
            product, _ = Product.objects.update_or_create(
                sku=item["sku"],
                defaults={
                    "name": item["name"],
                    "slug": slugify(f"{item['sku']}-{item['name']}"),
                    "short_description": item["short_description"],
                    "description": item["description"],
                    "brand": item["brand"],
                    "image_url": item["image_url"],
                    "price": item["price"],
                    "discount_percent": item["discount_percent"],
                    "stock": item["stock"],
                    "sold_count": item["sold_count"],
                    "rating_avg": item["rating_avg"],
                    "rating_count": item["rating_count"],
                    "is_active": True,
                    "domain": item["domain"],
                    "category": item["category"],
                },
            )

            if item["domain"] == "book":
                Book.objects.update_or_create(product=product, defaults=item["detail"])
            elif item["domain"] == "electronics":
                Electronics.objects.update_or_create(product=product, defaults=item["detail"])
            elif item["domain"] == "fashion":
                Fashion.objects.update_or_create(product=product, defaults=item["detail"])

            self.stdout.write(self.style.SUCCESS(f"Seeded product: {product.name}"))

        self.stdout.write(self.style.SUCCESS("Product seed completed."))
